# Generated by Django 4.0 on 2022-01-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='Image',
            new_name='image',
        ),
    ]
