# Generated by Django 4.0 on 2022-01-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_image_blogs_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='image',
            new_name='Image',
        ),
    ]
