# Generated by Django 4.0 on 2022-01-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogapp', '0005_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blogs',
        ),
    ]
