# Generated by Django 4.0 on 2022-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_rename_blogs_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='datetime',
            new_name='DateTime',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
