# Generated by Django 4.0 on 2022-01-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Image',
            new_name='image',
        ),
    ]
