# Generated by Django 4.0 on 2022-02-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_blogpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
